#!/usr/bin/env bash
# Tesla Android module
# Written by Michał Gapiński
# GPL V3
########

set -x
set -e

source /common.sh
install_cleanup_trap

cd /home/${BASE_USER}

echo iptables-persistent iptables-persistent/autosave_v4 boolean true | sudo debconf-set-selections
echo iptables-persistent iptables-persistent/autosave_v6 boolean true | sudo debconf-set-selections

apt-get update && \
    apt-get install -y --no-install-recommends \
    wget \
    git \
    make \
    build-essential \
    libevent-dev \
    libjpeg9-dev \
    libbsd-dev \
    iptables-persistent \
    hostapd \
    bridge-utils \
    urfkill
        
git clone --depth=1 https://github.com/pikvm/ustreamer && \
    cd ustreamer && \
    make && \
    make && make install && \
    cd /home/${BASE_USER}

rm -rf ustreamer

unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
unpack /filesystem/etc /etc

systemctl enable hostapd.service
systemctl enable ustreamer.service

echo 'dtoverlay=tc358743' >> /boot/config.txt
echo 'start_x=1' >> /boot/config

curl -L https://install.pi-hole.net | sudo PIHOLE_SKIP_OS_CHECK=true bash /dev/stdin --unattended

cd /var/www
mv html html-old
git clone https://github.com/tesla-android/flutter-app.git -b release html
mv html-old/pihole html
mv html-old/admin html
rm -rf html-old
cd /home/${BASE_USER}

rm -rf cd /etc/lighttpd/lighttpd.conf
mv /etc/lighttpd/lighttpd.conf.new /etc/lighttpd/lighttpd.conf

rfkill unblock wifi